version: "1"

services:
  comfyui:
    build: .

    environment:
      - NVIDIA_VISIBLE_DEVICES=all

    ports:
      - 80:80
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
